name: nexus-cluster

services:
  nexus-1:
    build:
      context: ./
    container_name: nexus-1
    ports:
      - "8081:8081"
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8081/actuator/health || exit 1" ]
      start_period: 20s
      interval: 5s
      timeout: 20s
      retries: 10
    volumes:
      - mcp-vector-data:/app/data
    environment:
      - SPRING_AI_VECTORSTORE_PATH=/app/data/vectorstore.json
    restart: unless-stopped

  nexus-2:
    build:
      context: ./
    container_name: nexus-2
    ports:
      - "8082:8081"

    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8081/actuator/health || exit 1" ]
      start_period: 20s
      interval: 5s
      timeout: 20s
      retries: 10
    volumes:
      - mcp-vector-data:/app/data
    environment:
      - SPRING_AI_VECTORSTORE_PATH=/app/data/vectorstore.json
    restart: unless-stopped

volumes:
  mcp-vector-data: