name: nexus-cluster

services:
  nexus-1:
    build:
      context: ./
    container_name: nexus-1
    ports:
      - "8081:8081"
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8081/actuator/health || exit 1" ]
      start_period: 20s
      interval: 5s
      timeout: 20s
      retries: 10
    environment:
      - SPRING_AI_OPENAI_API_KEY=yAIzaSyCTcYdEcLMEKTajtZAgTtefHrpRWTbw55A
      - SPRING_AI_OPENAI_EMBEDDING.API_KEY=yAIzaSyCTcYdEcLMEKTajtZAgTtefHrpRWTbw55A
      - REPLICA_ID=1
      - SERVER_PORT=8081
    restart: unless-stopped
    networks:
      - nexus-dev
    depends_on:
      postgres:
        condition: service_healthy

  nexus-2:
    build:
      context: ./
    container_name: nexus-2
    ports:
      - "8082:8082"
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8081/actuator/health || exit 1" ]
      start_period: 20s
      interval: 5s
      timeout: 20s
      retries: 10
    environment:
      - SPRING_AI_OPENAI_API_KEY=yAIzaSyCTcYdEcLMEKTajtZAgTtefHrpRWTbw55A
      - SPRING_AI_OPENAI_EMBEDDING.API_KEY=yAIzaSyCTcYdEcLMEKTajtZAgTtefHrpRWTbw55A
      - REPLICA_ID=2
      - SERVER_PORT=8082
    restart: unless-stopped
    networks:
      - nexus-dev
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: pgvector/pgvector:pg17
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: nexus-ai
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - nexus-dev
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "nexus", "-u", "root", "-p", "root" ]
      start_period: 15s
      interval: 5s
      timeout: 30s
      retries: 5
    ports:
      - "5432:5432"

  adminer:
    image: adminer:latest
    container_name: adminer
    ports:
      - "5433:8080"
    networks:
      - nexus-dev
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    depends_on:
      - postgres

volumes:
  postgres-data:

networks:
  nexus-dev:
    external: true