name: nexus-cluster

services:
  nexus-1:
    build:
      context: ./
    container_name: nexus-1
    ports:
      - "8081:8081"
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8081/actuator/health || exit 1" ]
      start_period: 20s
      interval: 5s
      timeout: 20s
      retries: 10
    volumes:
      - mcp-vector-data:/app/data
    environment:
      - SPRING_AI_VECTORSTORE_PATH=/app/data/vectorstore.json
      - REPLICA_ID=1
      - SERVER_PORT=8081
    restart: unless-stopped
    networks:
      - nexus-dev

  nexus-2:
    build:
      context: ./
    container_name: nexus-2
    ports:
      - "8082:8082"

    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8081/actuator/health || exit 1" ]
      start_period: 20s
      interval: 5s
      timeout: 20s
      retries: 10
    volumes:
      - mcp-vector-data:/app/data
    environment:
      - SPRING_AI_VECTORSTORE_PATH=/app/data/vectorstore.json
      - REPLICA_ID=2
      - SERVER_PORT=8082
    restart: unless-stopped
    networks:
      - nexus-dev

volumes:
  mcp-vector-data:

networks:
  nexus-dev:
    external: true