spring:
  application:
    name: Nexus
  config:
    import: "configserver:"
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config
      fail-fast: true
      retry:
        initial-interval: 1000
        max-interval: 3000
        multiplier: 1.1
        max-attempts: 10
  ai:
    mcp:
      server:
        enabled: true
        base-url: /api
        type: sync
        sse-endpoint: /sse
        sse-message-endpoint: /mcp/messages
        capabilities:
          completion: true
          prompt: true
          tool: true
          resource: true
        name: mcp-server
        instructions: "Use the MCP server to interact with AI capabilities."
        stdio: false
        version: 1.0.0
  profiles:
    active: dev

eureka:
  client:
    service-url:
      defaultZone: http://eureka-1:8761/eureka, http://eureka-2:8762/eureka
    register-with-eureka: true
    fetch-registry: true
    initial-instance-info-replication-interval-seconds: 0
    registry-fetch-interval-seconds: 5
    instance-info-replication-interval-seconds: 5
  instance:
    instance-id: nexus-${REPLICA_ID:1}
    hostname: nexus-${REPLICA_ID:1}
    appname: nexus
