spring:
  application:
    name: "Nexus"
  profiles:
    active: dev
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config
      fail-fast: true
      retry:
        initial-interval: 1000
        max-interval: 2000
        multiplier: 1.1
        max-attempts: 6