spring:
  application:
    name: Nexus
  config:
    import: "configserver:"
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config
      fail-fast: true
      retry:
        initial-interval: 1000
        max-interval: 3000
        multiplier: 1.1
        max-attempts: 10
  ai:
    mcp:
      server:
        enabled: true
        base-url: /api
        type: sync
        sse-endpoint: /sse
        sse-message-endpoint: /mcp/messages
        capabilities:
          completion: true
          prompt: true
          tool: true
          resource: true
        name: mcp-server
        instructions: "Use the MCP server to interact with AI capabilities."
        stdio: false
        version: 1.0.0
  profiles:
    active: dev