spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/nexus-ai
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
  ai:
    vectorstore:
      pgvector:
        index-type: hnsw
        dimensions: 1536
        distance-type: cosine_distance
        initialize-schema: true
        id-type: uuid

  application:
    name: nexus
  config:
    import: "configserver:"
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config
      fail-fast: true
      retry:
        initial-interval: 1000
        max-interval: 3000
        multiplier: 1.1
        max-attempts: 10

  main:
    web-application-type: reactive
  profiles:
    active: dev

eureka:
  client:
    service-url:
      defaultZone: http://eureka-1:8761/eureka, http://eureka-2:8762/eureka
    register-with-eureka: true
    fetch-registry: true
    initial-instance-info-replication-interval-seconds: 0
    registry-fetch-interval-seconds: 5
    instance-info-replication-interval-seconds: 5
  instance:
    instance-id: nexus-${REPLICA_ID:1}
    hostname: nexus-${REPLICA_ID:1}
    appname: nexus

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: "*"
    access:
      default: unrestricted